# Generated by Django 4.1.7 on 2023-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usertype_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='Typeid',
            field=models.IntegerField(),
        ),
    ]
